typography_spectrum: 0.9121157908812165
color:
  brandStrength: 0.4465712585952133
  lightness: 0.7948157505597919
  saturation: 0.6384574002586305
  rhythmicContrast: 0.34583342960104346
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.4163538753055036
name: modern muse
navigation:
  - name: Inside the Mansion in Ex Machina
    id: 7e52dbbc-3b97-4b4d-a0e8-d7bccdcff367
    type: content
  - name: 'Finlandia Caviar Shop and Restaurant, Helsinki, Finland '
    id: bfe4c523-6110-4161-8989-5d912735e63c
    type: content
  - name: Behind The Waldorf Astoria Bar Book's Brand New Update
    id: b1676fec-8293-4320-a4c4-5c4362ac2273
    type: content
  - name: BMW E30 TM Concept30 Car Concept by TMcars
    id: 688c9108-501b-4074-b088-6df33762100a
    type: content
  - name: 'Reduced Spoke Bicycles : Conceptual Bike'
    id: 11a30d24-2448-49cb-bfb2-269dac802a90
    type: content
  - name: 'Wandering: New York'
    id: 91d153d9-2acc-432f-a567-f8abe8a720c9
    type: content
  - name: 3sixteen + Herman Miller
    id: 6abfac35-5b8e-4295-8ca9-a52e1a303ab9
    type: content
  - name: 'Coming clean: Dirty Lemon makes detoxing a little easier.'
    id: 7133534f-1819-4b07-9cf9-0472f49ed132
    type: content
title: Lifestyle
description: When only the best will do
