typography_spectrum: 0.9121157908812165
color:
  brandStrength: 0.4465712585952133
  lightness: 0.7948157505597919
  saturation: 0.6384574002586305
  rhythmicContrast: 0.34583342960104346
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.4163538753055036
name: modern muse
navigation:
  - name: Inside the Mansion in Ex Machina
    id: 7e52dbbc-3b97-4b4d-a0e8-d7bccdcff367
    type: content
  - name: 'Finlandia Caviar Shop and Restaurant, Helsinki, Finland '
    id: bfe4c523-6110-4161-8989-5d912735e63c
    type: content
title: Lifestyle
description: When only the best will do
